from core.crud_base import CrudBase
from core.database import conectar_supabase
from core.validator import Validator

id_notificacao bigint generated by default as identity primary key,
    id_usuario bigint,
    titulo varchar(90),
    mensagem varchar(150),
    data_envio
 
class pedido(CrudBase):
    table = "notificacoes"
    primary_key = "id_notificacao" 
    fields = [
        "id_usuario",
        "titulo",
        "mensagem",
        "data_enviar"
    ]
 
    def __init__(self, id_usuario, titulo, mensagem, data_enviar):
        self.id_usuario = id_usuario
        self.titulo = titulo
        self.mensagem = mensagem
        self.data_enviar = data_enviar
 
    def validate(self):
        erros = [
            Validator.required(self.titulo, "titulo"),
            Validator.required(self.mensagem, "mensagem"),
            Validator.required(self.data_enviar, "data_enviar")
        ]
        return [erro for erro in erros if erro]
                
                
    @classmethod
    def safe_delete(cls, id):
        supabase = conectar_supabase()
        # Busca notificações e verifica se ele existe
        notificacao = cls.find_by_id(id)
        if not notificacao:
            raise ValueError("notificação não encontrada.")
        if cls.has_related_records(id):
            raise ValueError("Não é possível excluir a notificação porque possui tabelas vinculadas.")
        cls.delete(id)

    @classmethod
    def buscar_por_notifcacao(cls, id_notificacao):
        supabase = conectar_supabase()
        # Busca notificações de um usuário no banco e retorna uma instância da classe
        db = Database.get_client()
        res = db.table("notificacoes").select("*").eq("id", id_notificacao).execute()
        if res.data:
            d = res.data[0]
            return cls(id=d['id'], id_usuario=d['id_usuario'], titulo=d['titulo'], mensagem=d['mensagem'], data_enviar=d['data_enviar'])
        return None
    
    def inserir_atualizar_salvar(self):
        supabase = conectar_supabase()
        # Insere ou atualiza notificações
        dados = {"id_usuario": self.id_usuario, "titulo": self.titulo, "mensagem": self.mensagem, "data_enviar": self.data_enviar}
        if self.id:
            return self.db.table("notificacoes").update(dados).eq("id", self.id).execute()
        else:
            return self.db.table("notificacoes").insert(dados).execute()