from core.crud_base import CrudBase
from core.database import conectar_supabase
from core.validator import Validator
 
id_sensor bigint generated by default as identity primary key,
    id_camara bigint,
    id_area bigint,
    tipo varchar(50),

class Sensor(CrudBase):
    table = "sensor"
    primary_key = "id_sensor" 
    fields = [
        "id_camara_fria",
        "id_area",
        "modelo",
        "localizacao",
        "descricao",
        "tipo"
    ]
 
    def __init__(self, id_camara_fria, id_area, modelo, localizacao, descricao, tipo, id=None, id_sensor=None, **kwargs):
        self.id_area = id_area
        self.id_camara_fria = id_carama_fria
        self.modelo = modelo
        self.localizacao = localizacao
        self.descricao = descricao
        self.tipo = tipo
        self.db = Database.get_client() # Pega o cliente do Supabase
        self.id = id or id_sensor
        self.id_sensor = self.id
        self.db = database.conectar_supabase()  # Conecta o cliente do Supabase
 
    @classmethod
    def find_all(cls, order_by=None):
        if order_by is None:
            order_by = cls.primary_key
        supabase = conectar_supabase()
        response = supabase.table(cls.table).select("*").order(order_by).execute()
        return response.data

    @classmethod
    def find_by_id(cls, id):
        supabase = conectar_supabase()
        response = supabase.table(cls.table).select("*").eq(cls.primary_key, id).execute()
        return response.data[0] if response.data else None

    @classmethod
    def delete(cls, id):
        supabase = conectar_supabase()
        response = supabase.table(cls.table).delete().eq(cls.primary_key, id).execute()
        return response.data

    def insert(self):
        supabase = conectar_supabase()
        dados = {campo: getattr(self, campo) for campo in self.fields}
        response = supabase.table(self.table).insert(dados).execute()
        return response.data

    def update(self, id):
        supabase = conectar_supabase()
        dados = {campo: getattr(self, campo) for campo in self.fields}
        response = supabase.table(self.table).update(dados).eq(self.primary_key, id).execute()
        return response.data

    def validate(self):
        erros = [
            Validator.required(self.modelo, "modelo"),
            Validator.required(self.localizacao, "localizacao"),
            Validator.required(self.descricao, "descricao"),
            Validator.required(self.tipo, "tipo")
        ]
        return [erro for erro in erros if erro]
                    
    @classmethod
    def safe_delete(cls, id):
        supabase = conectar_supabase()
        devolucao = cls.find_by_id(id)
        if not devolucao:
            raise ValueError("Sensor não encontrado.")
        if cls.has_related_records(id):
            raise ValueError("Não é possível excluir o sensor porque possui tabelas vinculadas.")
        cls.delete(id)

    @classmethod
    def buscar_por_sensor(cls, id_sensor):
        supabase = conectar_supabase()
        response = supabase.table("sensores").select("*").eq(cls.primary_key, id_sensor).execute()
        
        if response.data:
            d = response.data[0]
            return cls(
                id=d.get('id_sensor'),
                id_camara_fria=d.get('id_camara_fria'),
                id_area=d.get('id_area'),
                modelo=d.get('modelo'),
                localizacao=d.get('localizacao'),
                descricao=d.get('descricao'),
                tipo=d.get('tipo')
            )
        return None
    
    def inserir_sensor(self):
        supabase = conectar_supabase()
        dados = {campo: getattr(self, campo) for campo in self.fields}
        response = supabase.table(self.table).insert(dados).execute()
        return response.data

 
 
 