from core.crud_base import CrudBase
from core.database import conectar_supabase
from core.validator import Validator

id_registro bigint generated by default as identity primary key,
    id_sensor bigint,
    valor numeric(6,2) not null,
    data_hora timestamp,
    status_sensor varchar(30),
 
class Temperaturas_controladas(CrudBase):
    table = "temperaturas_controladas"
    primary_key = "id_registro_temperatura" 
    fields = [
        "id_sensor",
        "valor",
        "data_hora",
        "status_sensor"
    ]
    
    def __init__(self, id_sensor, valor, data_hora, status_sensor,  id=None, id_registro_temperatura=None, **kwargs):
        self.id_sensor = id_sensor
        self.valor = valor
        self.data_hora = dat_hor
        self.status_sensor = status_sensor
        self.db = Database.get_client() # Pega o cliente do Supabase
        self.id = id or id_registro_temperatura
        self.id_registro_temperatura = self.id
        self.db = database.conectar_supabase()  # Pega o cliente do Supabase
 
    @classmethod
    def find_all(cls, order_by=None):
        if order_by is None:
            order_by = cls.primary_key
        supabase = conectar_supabase()
        response = supabase.table(cls.table).select("*").order(order_by).execute()
        return response.data

    @classmethod
    def find_by_id(cls, id):
        supabase = conectar_supabase()
        response = supabase.table(cls.table).select("*").eq(cls.primary_key, id).execute()
        return response.data[0] if response.data else None

    @classmethod
    def delete(cls, id):
        supabase = conectar_supabase()
        response = supabase.table(cls.table).delete().eq(cls.primary_key, id).execute()
        return response.data

    def insert(self):
        supabase = conectar_supabase()
        dados = {campo: getattr(self, campo) for campo in self.fields}
        response = supabase.table(self.table).insert(dados).execute()
        return response.data

    def update(self, id):
        supabase = conectar_supabase()
        dados = {campo: getattr(self, campo) for campo in self.fields}
        response = supabase.table(self.table).update(dados).eq(self.primary_key, id).execute()
        return response.data

    def validate(self):
        erros = [
            Validador.required(self.valor, "valor"),
            Validator.required(self.data_hora, "data_hora")
            validator.required(self.status_sensor, "status_sensor"),
        ]
        return [erro for erro in erros if erro]
                    
    @classmethod
    def safe_delete(cls, id):
        supabase = conectar_supabase()
        devolucao = cls.find_by_id(id)
        if not devolucao:
            raise ValueError("Registro de tempertura não encontrado.")
        if cls.has_related_records(id):
            raise ValueError("Não é possível excluir o registro de temepratura porque possui tabelas vinculadas.")
        cls.delete(id)

    @classmethod
    def buscar_por_registro_temepratura(cls, id_saida):
        supabase = conectar_supabase()
        response = supabase.table("temperatura_controladas").select("*").eq(cls.primary_key, id_registro_temperatura).execute()
        
        if response.data:
            d = response.data[0]
            return cls(
                id=d.get('id_registro_temperatura'),
                id_sensor=d.get('id_sensor'),
                valor=d.get('valor'),
                data_hora=d.get('dat_hora')
                status_sensor=d.get('status_sensor'),
            )
        return None
    
    def inserir_registro_temperatura(self):
        supabase = conectar_supabase()
        dados = {campo: getattr(self, campo) for campo in self.fields}
        response = supabase.table(self.table).insert(dados).execute()
        return response.data

 